### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mugane**
I don't think there's such a thing as cygwin32-gcc-g++ or cygwin32-gcc-core 
```
$ cygcheck -c | grep -i gcc
gcc-core             11.4.0-1           OK
gcc-fortran          11.4.0-1           OK
gcc-g++              11.4.0-1           OK
gcc-objc             11.4.0-1           OK
gcc-objc++           11.4.0-1           OK
libgcc1              11.3.0-1           OK
```

### CODE REVIEW

**Comment by Mugane** [comment]
May also want to add that it is best to use Powershell (as Admin) to install these packages for cygwin if using cyg-get:
```
cyg-get gcc-g++ gcc-core make gcc-fortran gcc-objc gcc-objc++ libkrb5-devel libkrb5_3 libreadline-devel libssl-devel libwrap-devel tcp_wrappers
```
If you don't use powershell, and try to install from cygwin itself (even as Administrator) you may run into gnarly cryptic missing dll errors and end up needing to remove/reinstall cygwin itself to correct the problems.

If users don't have cygwin, I recommend [chocolatey](https://chocolatey.org/install) (again from Powershell as admin):
```
choco install -y cygwin cyg-get
```

**Comment by Mugane** [comment]
This is my entire `make` output btw if anyone wants to review deprecations and warnings
```
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o socat.o socat.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioinitialize.o xioinitialize.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiohelp.o xiohelp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioparam.o xioparam.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiodiag.o xiodiag.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioopen.o xioopen.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioopts.o xioopts.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiosignal.o xiosignal.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiosigchld.o xiosigchld.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioread.o xioread.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiowrite.o xiowrite.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiolayer.o xiolayer.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioshutdown.o xioshutdown.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioclose.o xioclose.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xioexit.o xioexit.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-process.o xio-process.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-fd.o xio-fd.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-fdnum.o xio-fdnum.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-stdio.o xio-stdio.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-pipe.o xio-pipe.c
xio-pipe.c: In function ‘xio_chk_pipesz’:
xio-pipe.c:203:13: warning: unused variable ‘pipesz’ [-Wunused-variable]
  203 |         int pipesz;
      |             ^~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-socketpair.o xio-socketpair.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-gopen.o xio-gopen.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-creat.o xio-creat.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-file.o xio-file.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-named.o xio-named.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-socket.o xio-socket.c
xio-socket.c: In function ‘xiolog_ancillary_socket’:
xio-socket.c:1761:20: warning: unused variable ‘tv’ [-Wunused-variable]
 1761 |    struct timeval *tv;
      |                    ^~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-interface.o xio-interface.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-listen.o xio-listen.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-unix.o xio-unix.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-vsock.o xio-vsock.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-ip.o xio-ip.c
xio-ip.c: In function ‘xiolog_ancillary_ip’:
xio-ip.c:486:9: warning: unused variable ‘scratch2’ [-Wunused-variable]
  486 |    char scratch2[16];
      |         ^~~~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-ip4.o xio-ip4.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-ip6.o xio-ip6.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-ipapp.o xio-ipapp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-tcp.o xio-tcp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-sctp.o xio-sctp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-dccp.o xio-dccp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-rawip.o xio-rawip.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-posixmq.o xio-posixmq.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-socks.o xio-socks.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-socks5.o xio-socks5.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-proxy.o xio-proxy.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-udp.o xio-udp.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-udplite.o xio-udplite.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-progcall.o xio-progcall.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-exec.o xio-exec.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-system.o xio-system.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-shell.o xio-shell.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-termios.o xio-termios.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-readline.o xio-readline.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-pty.o xio-pty.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-openssl.o xio-openssl.c
xio-openssl.c: In function ‘_xioopen_openssl_listen’:
xio-openssl.c:782:16: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  782 |                Msg4(level, "SSL_accept(): %s / %s / %s / %s", error_string,
      |                ^~~~
In file included from sysincludes.h:198,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/err.h:459:35: note: declared here
  459 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
xio-openssl.c: In function ‘_xioopen_openssl_prepare’:
xio-openssl.c:1300:7: warning: ‘DH_new’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1300 |       dh = DH_new();
      |       ^~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/dh.h:203:27: note: declared here
  203 | OSSL_DEPRECATEDIN_3_0 DH *DH_new(void);
      |                           ^~~~~~
xio-openssl.c:1305:13: warning: ‘DH_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1305 |             DH_free(dh);
      |             ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/dh.h:204:28: note: declared here
  204 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
xio-openssl.c:1318:7: warning: ‘DH_set0_pqg’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1318 |       if (!DH_set0_pqg(dh, p, NULL, g)) {
      |       ^~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/dh.h:259:27: note: declared here
  259 | OSSL_DEPRECATEDIN_3_0 int DH_set0_pqg(DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g);
      |                           ^~~~~~~~~~~
xio-openssl.c:1319:15: warning: ‘DH_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1319 |               DH_free(dh);
      |               ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/dh.h:204:28: note: declared here
  204 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
xio-openssl.c:1336:7: warning: ‘DH_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1336 |       DH_free(dh);
      |       ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/dh.h:204:28: note: declared here
  204 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
xio-openssl.c:1355:7: warning: ‘EC_KEY_new_by_curve_name’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1355 |       ecdh = EC_KEY_new_by_curve_name(nid);
      |       ^~~~
In file included from /usr/include/openssl/x509.h:33,
                 from /usr/include/openssl/ssl.h:31,
                 from sysincludes.h:197,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/ec.h:998:31: note: declared here
  998 | OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new_by_curve_name(int nid);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
xio-openssl.c: In function ‘xioSSL_connect’:
xio-openssl.c:2022:16: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 2022 |                Msg4(level, "SSL_connect(): %s / %s / %s / %s", error_string,
      |                ^~~~
In file included from sysincludes.h:198,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/err.h:459:35: note: declared here
  459 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
xio-openssl.c: In function ‘xioread_openssl’:
xio-openssl.c:2082:16: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 2082 |                Error4("SSL_read(): %s / %s / %s / %s", error_string,
      |                ^~~~~~
In file included from sysincludes.h:198,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/err.h:459:35: note: declared here
  459 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
xio-openssl.c: In function ‘xiowrite_openssl’:
xio-openssl.c:2141:16: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 2141 |                Error4("SSL_write(): %s / %s / %s / %s", error_string,
      |                ^~~~~~
In file included from sysincludes.h:198,
                 from xiosysincludes.h:11,
                 from xio-openssl.c:7:
/usr/include/openssl/err.h:459:35: note: declared here
  459 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-streams.o xio-streams.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-namespaces.o xio-namespaces.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-ascii.o xio-ascii.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xiolockfile.o xiolockfile.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-tcpwrap.o xio-tcpwrap.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-fs.o xio-fs.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o xio-tun.o xio-tun.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o error.o error.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o dalan.o dalan.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -c -D CC=\"gcc\" -o procan.o procan.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o procan-cdefs.o procan-cdefs.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o hostan.o hostan.c
hostan.c:22:12: warning: ‘vsockan’ declared ‘static’ but never defined [-Wunused-function]
   22 | static int vsockan(FILE *outfile);
      |            ^~~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o fdname.o fdname.c
fdname.c: In function ‘sockname’:
fdname.c:253:8: warning: unused variable ‘rc’ [-Wunused-variable]
  253 |    int rc;
      |        ^~
fdname.c:230:31: warning: unused variable ‘protoentp’ [-Wunused-variable]
  230 |    struct protoent protoent, *protoentp;
      |                               ^~~~~~~~~
fdname.c:230:20: warning: unused variable ‘protoent’ [-Wunused-variable]
  230 |    struct protoent protoent, *protoentp;
      |                    ^~~~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o sysutils.o sysutils.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o utils.o utils.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o nestlex.o nestlex.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o vsnprintf_r.o vsnprintf_r.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o snprinterr.o snprinterr.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o filan.o filan.c
filan.c: In function ‘ipan’:
filan.c:799:14: warning: unused variable ‘optlen’ [-Wunused-variable]
  799 |    socklen_t optlen = sizeof(optproto);
      |              ^~~~~~
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o sycls.o sycls.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o sslcls.o sslcls.c
sslcls.c: In function ‘sycPEM_read_bio_DHparams’:
sslcls.c:455:4: warning: ‘PEM_read_bio_DHparams’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  455 |    result = PEM_read_bio_DHparams(bp, x, cb, u);
      |    ^~~~~~
In file included from /usr/include/openssl/ssl.h:36,
                 from sysincludes.h:197,
                 from sslcls.c:13:
/usr/include/openssl/pem.h:469:1: note: declared here
  469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
      | ^~~~~~~~~~~~~~~~~~~
ar r libxio.a xioinitialize.o xiohelp.o xioparam.o xiodiag.o xioopen.o xioopts.o xiosignal.o xiosigchld.o xioread.o xiowrite.o xiolayer.o xioshutdown.o xioclose.o xioexit.o xio-process.o xio-fd.o xio-fdnum.o xio-stdio.o xio-pipe.o xio-socketpair.o xio-gopen.o xio-creat.o xio-file.o xio-named.o xio-socket.o xio-interface.o xio-listen.o xio-unix.o xio-vsock.o xio-ip.o xio-ip4.o xio-ip6.o xio-ipapp.o xio-tcp.o xio-sctp.o xio-dccp.o xio-rawip.o xio-posixmq.o xio-socks.o xio-socks5.o xio-proxy.o xio-udp.o xio-udplite.o xio-progcall.o xio-exec.o xio-system.o xio-shell.o xio-termios.o xio-readline.o xio-pty.o xio-openssl.o xio-streams.o xio-namespaces.o xio-ascii.o xiolockfile.o xio-tcpwrap.o xio-fs.o xio-tun.o error.o dalan.o procan.o procan-cdefs.o hostan.o fdname.o sysutils.o utils.o nestlex.o vsnprintf_r.o snprinterr.o filan.o sycls.o sslcls.o
ar: creating libxio.a
ranlib libxio.a
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.   -o socat socat.o libxio.a -lwrap -lutil  -lreadline  -lssl -lcrypto -lcrypto
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o procan_main.o procan_main.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.   -o procan procan_main.o procan.o procan-cdefs.o hostan.o error.o sycls.o sysutils.o utils.o vsnprintf_r.o snprinterr.o -lwrap -lutil  -lreadline  -lssl -lcrypto -lcrypto
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.  -I.   -c -o filan_main.o filan_main.c
gcc -O -D_GNU_SOURCE -Wall -Wno-parentheses  -DHAVE_CONFIG_H -I.   -o filan filan_main.o filan.o fdname.o error.o sycls.o sysutils.o utils.o vsnprintf_r.o snprinterr.o -lwrap -lutil  -lreadline  -lssl -lcrypto -lcrypto
```

**Comment by valorisa** [comment]
Can you verify please. Thanks
https://ardupilot.org/dev/docs/building-setup-windows-cygwin.html

**Comment by valorisa** [comment]
Hello Mugane,
Thank you for your relevants comments aimed at improving or optimizing the installation of socat for Windows via Cygwin.
All of the packages mentioned do exist in Cygwin's package selection manager. I'd be more of a fan of leaving them there and adding your remarks for some users who are looking for a specific installation of socat for the Windows environment.
: – gcc-g++

– gcc-core

– cygwin32-gcc-g++

– cygwin32-gcc-core

– make

– gcc-fortran

– gcc-objc

– gcc-objc++

– libkrb5-devel

– libkrb5_3

– libreadline-devel

– libssl-devel

– libwrap-devel

– tcp_wrappers

**Comment by valorisa** [comment]
C:\Users\<username>cygcheck -c | grep cygwin32-*
cygwin32                               2.10.0-1                     OK
cygwin32-binutils                      2.29-1                       OK
cygwin32-default-manifest              6.4-1                        OK
cygwin32-gcc-core                      6.4.0-1                      OK
cygwin32-gcc-g++                       6.4.0-1                      OK
cygwin32-w32api-headers                4.0.4-1                      OK
cygwin32-w32api-runtime                4.0.4-1                      OK

**Pull request merged**
